# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-17 12:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agreements', '0002_agreement_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='targeted_users',
            field=models.ManyToManyField(help_text='select users which should see the agreement.', related_name='user_agreements', to=settings.AUTH_USER_MODEL, verbose_name='targeted users'),
        ),
        migrations.AlterField(
            model_name='agreementtouser',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agreements.Agreement', verbose_name='Agreement'),
        ),
    ]
